version: 0.2


phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo installing dependancies
      - npm install
  build:
    commands:
      - echo building the app
      - npm run build
  post_build:
    commands:
      - echo build complete on `date`


artifacts:
  files:
    - '**/*'
